/* gdal_def.h.  Generated by cmake4gdal  */

/* Define if gdal used libz*/
#cmakedefine GDAL_USE_LIBZ

/* Define to 1 gdal used internal libz*/
#cmakedefine01 GDAL_USE_LIBZ_INTERNAL

/* Define if gdal used libcurl */
#cmakedefine GDAL_USE_CURL

/* Define if gdal used odbc */
#cmakedefine GDAL_USE_ODBC

/* Define if gdal used xmlreformat */
#cmakedefine GDAL_USE_XMLREFORMAT

/* Define if gdal used cpl */
#cmakedefine GDAL_USE_CPL

/* Define if pam enable in gdal */
#cmakedefine GDAL_PAM_ENABLED

/* Define if gdal use geos*/
#cmakedefine01 GDAL_HAVE_GEOS

/* Define if gdal use opencl*/
#cmakedefine GDAL_HAVE_OPENCL

/* Define if gdal use armadillo*/
#cmakedefine GDAL_HAVE_ARMADILLO

/* Define if gdal use iconv*/
#cmakedefine GDAL_HAVE_ICONV

/* Define if gdal use internal libtiff*/
#cmakedefine GDAL_USE_LIBTIFF_INTERNAL
#cmakedefine GDAL_HAVE_TIFF
#cmakedefine GDAL_BIGTIFF_SUPPORT
#cmakedefine GDAL_PIXARLOG_SUPPORT

/* Define if gdal use internal libjpeg*/
#cmakedefine GDAL_USE_LIBJPEG_INTERNAL
#cmakedefine GDAL_HAVE_JPEG
#cmakedefine GDAL_JPEG_SUPPORT
#cmakedefine GDAL_OJPEG_SUPPORT

/* Define if gdal use internal libpng*/
#cmakedefine GDAL_USE_LIBPNG_INTERNAL
#cmakedefine GDAL_HAVE_PNG

/* Define if gdal use internal libgif*/
#cmakedefine GDAL_USE_LIBGIF_INTERNAL
#cmakedefine GDAL_HAVE_GIF

#cmakedefine GDAL_HAVE_EXPAT
#cmakedefine GDAL_HAVE_SQLITE
#cmakedefine GDAL_HAVE_SPATIALITE
#cmakedefine GDAL_HAVE_PG
#cmakedefine GDAL_HAVE_SQLITE
#cmakedefine GDAL_HAVE_MYSQL
#cmakedefine GDAL_HAVE_BOOST
#cmakedefine GDAL_HAVE_HAVE_LIBKML
#cmakedefine GDAL_HAVE_HAVE_FREEXL

#cmakedefine GDAL_ENABLE_OGR
#cmakedefine OGR_USE_JSONC_INTERNAL

/*** RASTER FORMATS ***/
#cmakedefine GDAL_ENABLE_FRMT_GTIFF
#cmakedefine GDAL_ENABLE_FRMT_JPEG
#cmakedefine GDAL_ENABLE_FRMT_HFA
#cmakedefine GDAL_ENABLE_FRMT_BMP
#cmakedefine GDAL_ENABLE_FRMT_DIMAP
#cmakedefine GDAL_ENABLE_FRMT_MEM
#cmakedefine GDAL_ENABLE_FRMT_RAW
#cmakedefine GDAL_ENABLE_FRMT_VRT
#cmakedefine GDAL_ENABLE_FRMT_PNG
#cmakedefine GDAL_ENABLE_FRMT_GIF
#cmakedefine GDAL_ENABLE_FRMT_TIL
#cmakedefine GDAL_ENABLE_FRMT_OZI
#cmakedefine GDAL_ENABLE_FRMT_OZIMAP
#cmakedefine GDAL_ENABLE_FRMT_POSTGISRASTER
#cmakedefine GDAL_ENABLE_FRMT_ECW
#cmakedefine GDAL_ENABLE_FRMT_GEORASTER
#cmakedefine GDAL_ENABLE_FRMT_WMS
#cmakedefine GDAL_ENABLE_FRMT_AAIGRID
#cmakedefine GDAL_ENABLE_FRMT_AIG
#cmakedefine GDAL_ENABLE_FRMT_PDS
#cmakedefine GDAL_ENABLE_FRMT_HDF4
#cmakedefine GDAL_ENABLE_FRMT_HDF5
#cmakedefine GDAL_ENABLE_FRMT_E00GRID
#cmakedefine GDAL_ENABLE_FRMT_JDEM
#cmakedefine GDAL_ENABLE_FRMT_WCS
#cmakedefine GDAL_ENABLE_FRMT_PDF
#cmakedefine GDAL_ENABLE_FRMT_MrSID
#cmakedefine GDAL_ENABLE_FRMT_KMLSUPEROVERLAY
#cmakedefine GDAL_ENABLE_FRMT_L1B
#cmakedefine GDAL_ENABLE_FRMT_NGSGEOID
#cmakedefine GDAL_ENABLE_FRMT_NITF
#cmakedefine GDAL_ENABLE_FRMT_ISO8211
#cmakedefine GDAL_ENABLE_FRMT_SAGA
#cmakedefine GDAL_ENABLE_FRMT_JP2OpenJPEG
#cmakedefine GDAL_ENABLE_FRMT_ELAS
#cmakedefine GDAL_ENABLE_FRMT_CEOS
#cmakedefine GDAL_ENABLE_FRMT_CEOS2
#cmakedefine GDAL_ENABLE_FRMT_JAXAPALSAR
#cmakedefine GDAL_ENABLE_FRMT_GFF
#cmakedefine GDAL_ENABLE_FRMT_GFF
#cmakedefine GDAL_ENABLE_FRMT_BSB
#cmakedefine GDAL_ENABLE_FRMT_DTED
#cmakedefine GDAL_ENABLE_FRMT_ENVISAT
#cmakedefine GDAL_ENABLE_FRMT_ERS
#cmakedefine GDAL_ENABLE_FRMT_SDTS
#cmakedefine GDAL_ENABLE_FRMT_XPM
#cmakedefine GDAL_ENABLE_FRMT_AIRSAR
#cmakedefine GDAL_ENABLE_FRMT_RS2
#cmakedefine GDAL_ENABLE_FRMT_ILWIS
#cmakedefine GDAL_ENABLE_FRMT_SGI
#cmakedefine GDAL_ENABLE_FRMT_SRTMHGT
#cmakedefine GDAL_ENABLE_FRMT_LEVELLER
#cmakedefine GDAL_ENABLE_FRMT_TERRAGEN
#cmakedefine GDAL_ENABLE_FRMT_FIT
#cmakedefine GDAL_ENABLE_FRMT_RMF
#cmakedefine GDAL_ENABLE_FRMT_GSG
#cmakedefine GDAL_ENABLE_FRMT_COSAR
#cmakedefine GDAL_ENABLE_FRMT_TSX
#cmakedefine GDAL_ENABLE_FRMT_COASP
#cmakedefine GDAL_ENABLE_FRMT_R
#cmakedefine GDAL_ENABLE_FRMT_USGSDEM
#cmakedefine GDAL_ENABLE_FRMT_GXF
#cmakedefine GDAL_ENABLE_FRMT_NORTHWOOD
#cmakedefine GDAL_ENABLE_FRMT_ADRG
#cmakedefine GDAL_ENABLE_FRMT_BLX
#cmakedefine GDAL_ENABLE_FRMT_XYZ
#cmakedefine GDAL_ENABLE_FRMT_HF2
#cmakedefine GDAL_ENABLE_FRMT_CTG
#cmakedefine GDAL_ENABLE_FRMT_ZMAP
#cmakedefine GDAL_ENABLE_FRMT_IRIS


/*** VECTOR FORMATS ***/
#cmakedefine OGR_ENABLE_MITAB
#cmakedefine OGR_ENABLE_CSV
#cmakedefine OGR_ENABLE_DFX
#cmakedefine OGR_ENABLE_GEOJSON
#cmakedefine OGR_ENABLE_MEM
#cmakedefine OGR_ENABLE_VRT
#cmakedefine OGR_ENABLE_GPX
#cmakedefine OGR_ENABLE_SHP
#cmakedefine OGR_ENABLE_WFS
#cmakedefine OGR_ENABLE_PG
#cmakedefine OGR_ENABLE_SQLITE
#cmakedefine OGR_ENABLE_MYSQL
#cmakedefine OGR_ENABLE_LIBKML
#cmakedefine OGR_ENABLE_GML
#cmakedefine OGR_ENABLE_KML
#cmakedefine OGR_ENABLE_SXF
#cmakedefine OGR_ENABLE_S57
#cmakedefine OGR_ENABLE_OGDB
#cmakedefine OGR_ENABLE_XLS
#cmakedefine OGR_ENABLE_XLSX
#cmakedefine OGR_ENABLE_ODS
#cmakedefine OGR_ENABLE_AVC
#cmakedefine OGR_ENABLE_GME
#cmakedefine OGR_ENABLE_GMT
#cmakedefine OGR_ENABLE_GPSTrackMaker
#cmakedefine OGR_ENABLE_HTF
#cmakedefine OGR_ENABLE_DGN
#cmakedefine OGR_ENABLE_PGDump


