cmake_minimum_required (VERSION 2.8.10 FATAL_ERROR)

    set(GDAL_DATA "")
	if(GDAL_INSTALL_DATA_IN_VERSION)
	    set(GDAL_DATA ${CMAKE_INSTALL_PREFIX}/share/gdal/${GDAL_VERSION})
	    install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/data/ DESTINATION share/gdal/${GDAL_VERSION} FILES_MATCHING PATTERN "*.*")
	else()    
    	set(GDAL_DATA ${CMAKE_INSTALL_PREFIX}/share/gdal)
	    install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/data/ DESTINATION share/gdal FILES_MATCHING PATTERN "*.*")
	endif()
	set(INST_PREFIX ${CMAKE_INSTALL_PREFIX})
	set(INST_INCLUDE ${CMAKE_INSTALL_PREFIX}/include/gdal)
	set(OGR_ENABLED "no")
	if(GDAL_ENABLE_OGR)
	    set(OGR_ENABLED "yes")
    endif()
    set(CONFIG_LIBS "-L${INST_PREFIX}/lib -l${GDAL_LIB_NAME}")
    set(CONFIG_LIBS_INS "-L${INST_PREFIX}/lib -l${GDAL_LIB_NAME}")
    STRING(REPLACE ";" " " GDAL_FORMATS ${GDAL_FORMATS})
    STRING(REPLACE ";" " " LIBS ${LIBS})
    
    configure_file(${CMAKE_MODULE_PATH}/gdal-config.in.cmake ${GDAL_ROOT_BINARY_DIR}/gdal-config @ONLY)
    execute_process(COMMAND chmod 777 ${GDAL_ROOT_BINARY_DIR}/gdal-config)   
    configure_file(${CMAKE_MODULE_PATH}/gdal-config-inst.in.cmake ${GDAL_ROOT_BINARY_DIR}/gdal-config-inst @ONLY)    
    install(PROGRAMS ${GDAL_ROOT_BINARY_DIR}/gdal-config-inst DESTINATION bin RENAME gdal-config)

